export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const SET_ERROR = "SET_ERROR";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOADING = "SET_LOADING";
export const SET_TOTAL_RECORD = "SET_TOTAL_RECORD";
